export const tools = [
  {
    slug: "qr-code",
    href: "/tools/qr-code",
    number: "01",
    name: "QR code generator",
    summary:
      "Turn a website, review page, payment link, phone number, or short message into a downloadable QR code.",
    action: "Make a QR code",
    output: "Downloadable PNG + encoded content",
    category: "Marketing links",
    featured: true,
    mode: "browser",
    published: true,
  },
  {
    slug: "image-optimizer",
    href: "/tools/image-optimizer",
    number: "02",
    name: "Website image optimizer",
    summary:
      "Resize and compress a website photo on your device, compare the file size, and download the smaller version.",
    action: "Optimize an image",
    output: "Resized image + real size comparison",
    category: "Website performance",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "website-check",
    href: "/tools/website-check",
    number: "03",
    name: "PageSpeed website check",
    summary:
      "Test a public page on mobile or desktop. See Google PageSpeed scores, measurements, and the fixes worth looking at first.",
    action: "Run the website check",
    output: "Google data + plain-English priorities",
    category: "Website performance",
    featured: false,
    mode: "live",
    published: true,
  },
  {
    slug: "seo-check",
    href: "/tools/seo-check",
    number: "04",
    name: "Website SEO essentials check",
    summary: "Check the page information search engines rely on.",
    action: "Run the SEO check",
    output: "Search essentials + recommended fixes",
    category: "Website SEO",
    featured: false,
    mode: "n8n",
    published: true,
  },
  {
    slug: "broken-link-check",
    href: "/tools/broken-link-check",
    number: "05",
    name: "Broken link checker",
    summary: "Find broken and redirected links within a limited website crawl.",
    action: "Check the links",
    output: "Working, redirected + broken links",
    category: "Website health",
    featured: false,
    mode: "n8n",
    published: true,
  },
  {
    slug: "domain-health-check",
    href: "/tools/domain-health-check",
    number: "06",
    name: "Domain and email health check",
    summary: "Check public DNS addresses, mail routing, SPF, and DMARC records.",
    action: "Check the domain",
    output: "Website address + email DNS findings",
    category: "Website health",
    featured: false,
    mode: "n8n",
    published: true,
  },
  {
    slug: "social-preview-check",
    href: "/tools/social-preview-check",
    number: "07",
    name: "Social sharing preview check",
    summary: "Inspect the title, description, and image a shared link provides.",
    action: "Check a shared link",
    output: "Share preview + metadata findings",
    category: "Marketing links",
    featured: false,
    mode: "n8n",
    published: true,
  },
  {
    slug: "utm-builder",
    href: "/tools/utm-builder",
    number: "08",
    name: "Campaign link builder",
    summary:
      "Add clean campaign tags to a link so analytics can separate traffic from flyers, email, social posts, and ads.",
    action: "Build a tracked link",
    output: "Tagged URL + parameter summary",
    category: "Marketing links",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "contact-links",
    href: "/tools/contact-links",
    number: "09",
    name: "Call, text & email link builder",
    summary:
      "Create tap-to-call, prefilled text-message, and ready-to-email links for a website, QR code, or digital flyer.",
    action: "Build contact links",
    output: "Working links + HTML snippets",
    category: "Customer communication",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "email-signature",
    href: "/tools/email-signature",
    number: "10",
    name: "Email signature builder",
    summary:
      "Build a clean business email signature with clickable contact details and no image-hosting headache.",
    action: "Build a signature",
    output: "Visual signature + email-ready copy",
    category: "Customer communication",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "contrast-checker",
    href: "/tools/contrast-checker",
    number: "11",
    name: "Color contrast checker",
    summary:
      "Check whether one text-and-background color pair meets common WCAG contrast thresholds.",
    action: "Check two colors",
    output: "Contrast ratio + pass/fail thresholds",
    category: "Website accessibility",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "search-preview",
    href: "/tools/search-preview",
    number: "12",
    name: "Google search preview",
    summary:
      "Draft a page title, description, and main heading—then see how the listing may look before you publish it.",
    action: "Build a search listing",
    output: "Title, description, H1 + live preview",
    category: "Website SEO",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "copy-clarity",
    href: "/tools/copy-clarity",
    number: "13",
    name: "Website copy clarity check",
    summary:
      "Paste website wording and find long sentences, dense paragraphs, vague phrases, and missing next steps—without a fake grade.",
    action: "Check my wording",
    output: "Measured facts + specific editing actions",
    category: "Website copy",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "time-check",
    href: "/tools/time-check",
    number: "14",
    name: "Repetitive-task cost calculator",
    summary:
      "Put a real number on one repeated office task using its frequency, duration, and the value of the time it consumes.",
    action: "Calculate the task cost",
    output: "Monthly and yearly time + cost",
    category: "Business automation",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "automation-finder",
    href: "/tools/automation-finder",
    number: "15",
    name: "Automation opportunity finder",
    summary:
      "Choose the repetitive handoffs slowing the business down and build a practical trigger, action, human-checkpoint, and test plan.",
    action: "Find useful automations",
    output: "Prioritized implementation outline",
    category: "Business automation",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "local-schema",
    href: "/tools/local-schema",
    number: "16",
    name: "Local Business schema builder",
    summary:
      "Turn accurate business details into JSON-LD code that helps search engines understand the organization.",
    action: "Build business schema",
    output: "Copy-ready LocalBusiness JSON-LD",
    category: "Website SEO",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "review-text",
    href: "/tools/review-text",
    number: "17",
    name: "Review request kit",
    summary:
      "Turn a few job details into a same-day text, a polite follow-up, and an email asking for an honest review.",
    action: "Write the messages",
    output: "SMS, follow-up + email",
    category: "Customer trust",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "lead-response",
    href: "/tools/lead-response",
    number: "18",
    name: "New lead response kit",
    summary:
      "Create an immediate text, after-hours reply, email, and polite follow-up for a new customer inquiry.",
    action: "Write the responses",
    output: "Four ready-to-use messages",
    category: "Customer communication",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "website-brief",
    href: "/tools/website-brief",
    number: "19",
    name: "Website project brief builder",
    summary:
      "Organize the business, audience, pages, goals, and missing information into one useful website brief.",
    action: "Build a website brief",
    output: "Structured brief + missing-information list",
    category: "Website planning",
    featured: false,
    mode: "browser",
    published: true,
  },
  {
    slug: "review-reply",
    href: "/tools/review-reply",
    number: "20",
    name: "Customer review reply writer",
    summary:
      "Turn verified details into a professional public response to a positive, mixed, or negative customer review.",
    action: "Write a review reply",
    output: "Short + full response drafts",
    category: "Customer trust",
    featured: false,
    mode: "browser",
    published: true,
  },
] as const;

export type ToolSlug = (typeof tools)[number]["slug"];

export const publishedTools = tools.filter((tool) => tool.published);
export const pendingN8nTools = tools.filter(
  (tool) => tool.mode === "n8n" && !tool.published,
);
